# Generated by Django 2.2.14 on 2020-10-01 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_advuser_userpic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advuser',
            name='userpic',
        ),
    ]
