# Generated by Django 2.2.16 on 2020-10-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201006_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=50, verbose_name='Содержание'),
        ),
    ]
